# Generated by Django 4.1.3 on 2023-02-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name_plural': 'News'},
        ),
    ]
