# Generated by Django 4.1.3 on 2023-02-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_alter_gallery_page_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery_page',
            options={'ordering': ['-date']},
        ),
    ]
