# Generated by Django 4.1.3 on 2023-02-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_news_letter_rename_contact_us_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_letter',
            old_name='email',
            new_name='email_footer',
        ),
    ]
