# Generated by Django 4.1.3 on 2023-02-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_rename_email_news_letter_email_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_letter',
            old_name='email_footer',
            new_name='email',
        ),
    ]
