# Generated by Django 4.1.3 on 2023-02-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0005_rename_full_name_contact_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
