# Generated by Django 4.1.3 on 2023-02-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0006_rename_first_name_contact_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
