# Generated by Django 4.1.3 on 2023-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs_available',
            options={'verbose_name_plural': 'Jobs_available'},
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='tel',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs_available',
            name='vacancy',
            field=models.CharField(max_length=200, verbose_name='vacancy'),
        ),
    ]
