# Generated by Django 4.1.3 on 2023-02-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_alter_jobs_available_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
