# Generated by Django 4.1.3 on 2023-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_application_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
