# Generated by Django 4.1.3 on 2023-02-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_slide',
            name='title',
        ),
        migrations.RemoveField(
            model_name='gallery_slide',
            name='title',
        ),
    ]
