# Generated by Django 4.1.3 on 2023-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_event_slide_title_remove_gallery_slide_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_slide',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='first_slide',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='gallery_slide',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
