# Generated by Django 4.1.3 on 2023-03-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_event_slide_options_alter_first_slide_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='first_slide',
            options={},
        ),
    ]
