# Generated by Django 4.1.3 on 2023-03-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_first_slide_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_slide',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Recent_events'},
        ),
    ]
